### ISSUE TITLE
fm64.cpp OSC_CYCLE performance optimization

### ISSUE THREAD

**Issue by aminixduser** [dukesrg/logue-osc#15]
Hi Oleg,

on the develop-fm64 branch
I think I have a small improvement in the OSC_CYCLE.
I don't believe operator 1 ever modulates any other operator, so you can safely remove:

Assuming ALG_MOD1_MASK is for  operator 1 modulating another operator, 
       if (s_algorithm[i] & ALG_MOD1_MASK) modw0 += s_opval[5];   
may be removed, but looking at this I see   modw0 +=opval[5] , 
If opval[5] is the output of operator 6, it looks like the mask and operator orders are not aligned.
If that is the case all the lines with modulation need to be fixes so that the ALG_MOD<n>_MASK check results in modw0 +=s_opval[<n-1>]

Hope this helps

**Comment by dukesrg** [comment]
@aminixduser Yes this make sense, operator 1 is always a carrier. 
Operators processed in a reverse order, so opval[5] is OP1 output actually

**Comment by dukesrg** [comment]
Still not enough to enable feedback on -logues :(
