### ISSUE TITLE
Possible OSC_CYCLE improvement in fm64.cpp

### ISSUE THREAD

**Issue by aminixduser** [dukesrg/logue-osc#18]
@dukesrg 

In OSC_CYCLE,  in the MODn_MASK section again.

This idea may not work out, but I thought I'd mention it, because I think all the masks may be creating a bunch of
loads if the compiler isn't very smart.  
I just looked at the armv7-m Arch manual and it really only has 12 general purpose registers,. the others are used for address/stack pointers and the main PC.
The function has many variables so I imagine there are many loads going on.

I made the observation that MOD6_MASK makes algorithm[i] an odd value
so why not do this

uint8_t mask = algorithm[i];

else if (mask & (ALG_FBK_MASK - 1)) {
  if (mask % 2) modw0 += s_opval[0];   // if the compiler is smart it can do an odd compare and test in one instruction
  mask = mask >> 1;   //should take 1 cycle, no register move
  if (mask % 2) modw0 += s_opval[1];
  mask = mask >>1;

and so on ...

**Comment by dukesrg** [comment]
@aminixduser Yes this could make sence. The register pool is definitely exhausted so load/store operations steals a lot of performance.
Those calculations was inilially in the loop, but the third nested loop was slowing down the whole oscillator too, so I rolled out the loop.
ARM actually have the build in shift, so technically ((mask >> i) % 2) could be a single opcode command. I'll check the debug assembly output for different cases, thanks for the idea!

**Comment by dukesrg** [comment]
@aminixduser 
Nope, that's not gonna work like that, here is the debug listing:
```
        if (s_algorithm[i] & ALG_MOD5_MASK) modw0 += s_opval[1];
20004906:	0797      	lsls	r7, r2, #30
20004908:	bf44      	itt	mi
2000490a:	f8d0 723c 	ldrmi.w	r7, [r0, #572]	; 0x23c
2000490e:	19db      	addmi	r3, r3, r7
//        if (s_algorithm[i] & ALG_MOD4_MASK) modw0 += s_opval[2];
        if (s_algorithm[i] % 2) modw0 += s_opval[2];
20004910:	f1b8 0f00 	cmp.w	r8, #0
20004914:	d002      	beq.n	2000491c <_hook_cycle+0x138>
20004916:	f8d0 7240 	ldr.w	r7, [r0, #576]	; 0x240
2000491a:	443b      	add	r3, r7
        if (s_algorithm[i] & ALG_MOD3_MASK) modw0 += s_opval[3];
```
Compiler optimized single-bit mask with shifts, conditional additions to the phase performed based on the flag with no IP change. So load operation occurs only for the modulator output values in case of modulation is performed.
There is no parity condition in ARM so compiler did even worse Mod 2 makes the things even worse - zero-compare and explicit branch with relative IP. I wonder why ITT NE was not used though.
