### ISSUE TITLE
No sound on Minilogue XD

### ISSUE THREAD

**Issue by andredatele** [dukesrg/logue-osc#40]
Hi, 

I tried the pre-compiled files and also just compiled my own for the minilogue XD. I tried multiple FMxx osc, and it doesn't seem to matter whether I upload a mnlg/ntk/prlg file to the synth. There's no sound.
Changing any of the parameters has no effect - still no sound. I also tried multiple voices (poly/mono/duo/unison). 
Nothing seems to make a difference.

What's wrong here?

**Comment by snkws** [comment]
Same here, unfortunately.

**Comment by Sebo1971** [comment]
Simply use the Web App:
https://dukesrg.github.io/logue-osc/
Don't forget to upload the DX7 sysex banks, without them, FM64 does nothing...

**Comment by andredatele** [comment]
Thanks, got it working yesterday evening. Is there any way of making the osc files locally instead of using the web app? I tried using the FM64.sh sysex injector but couldn't make it work.

**Comment by Sebo1971** [comment]
Yes, you have to use FM64.sh, I didn't try it, I always use the web app...

**Comment by andredatele** [comment]
Was digging through some posts on the gearslutz thread. This seems to be it (haven't tested it yet):

# ./FM64.sh A.mnlgxdunit B.syx C.syx

A being the osc compiled file
B/C being the sysex DX7 banks.
